### PR TITLE
PlanningSystem is able to manage multiple planners + FF planner

### PR DESCRIPTION
**Pull request by dgerod**
It manages multiple planners, it is not necessary to recompile every time you want to change a planner. In addition, now it is possible to use the FF planner so the binary and and Plan Parser have been added.

Although it seems that solution to manage multiple planners will be a new node named PlannerInterface, this modification allows this functionality until the new node is created and PlanningSystem is updated.

See #61 for more information.

### CODE REVIEW

**Comment by dgerod** [comment]
After your modification about PlannerSystem and PlannerInterface, the only thing that could be interesting to add to ROSPlan is the FF planner and parser.

**Comment by m312z** [comment]
I've grabbed those files (FF parsing cpp and h) for integration into the devel branch. Planning, parsing, and dispatching are now properly separated into three nodes. I'll modify the FF code to create FFPlanInterface, which will publish as a string the plan produced by FF in PDDL format.

**Comment by dgerod** [comment]
OK

**Comment by dgerod** [comment]
@m312z, there was an error in the FF plan parser that I implemented.

Yesterday I fixed it, see [here](https://github.com/dgerod/ROSPlan/commit/7fe93fefc395c2cbc6817976be6dab4cba7cb2aa). I think that you don't integrate this code in ROSPlan yet so it is OK. However, when you will do , please, be sure to take the last version of the files. Thanks.

**Comment by m312z** [comment]
Hey @dgerod 
In the devel branch there is an FFPlannerInterface now, using some of your code:
https://github.com/KCL-Planning/ROSPlan/tree/devel/rosplan_planning_system/src/PlannerInterface

The plan parsing is separate from the planner interface, so the bug should not be present.

Thanks,
Michael

**Comment by dgerod** [comment]
Good :-) but  we will need a FF `PlannerParser` later, no? 

Why you split `PlannerInterface` and `PlanParser` when they are tightly coupled? Or do you expect that `PlannerInterface` using different planners generates a standard output file that will be always read using `PDDLSimplePlanParser` or `PDDLEsterelPlanParser`?

**Comment by m312z** [comment]
Two reasons for making the split:

(1) PlannerInterface will generate different outputs, but not as many as there are planners. For example, all planners that take part in the IPC should generate some standard PDDL plan output. Other planners generate something that can be easily modified into the correct syntax (without changing semantics).

(2) A plan from one planner could be parsed into number of different formats. For example, a PDDL2.1 plan from POPF can be a totally-ordered time-triggered plan, or a partially-ordered STN plan depending upon how it is parsed. Decoupling the planner interface from the plan parsing will avoid a lot of replicated code.

There will be some planner output and plan parsing combinations that are not valid. E.g., a contingent planner's output probably can't be read by PDDLSimplePlanParser.

**Comment by dgerod** [comment]
OK, thanks for the explanation.

**Pull request closed without merging**
